### ISSUE TITLE
target-opinion overlapping

### ISSUE THREAD

**Issue by GeneZC** [xuuuluuu/SemEval-Triplet-data#2]
I am wondering whether there exists the circumstance that we have TTTT but with only SSS.

**Comment by xuuuluuu** [comment]
This special case happened when the target(TTTT) has the same opinion words as one of the previous targets(either T/TT/TTT). I probably should remove these kinds of targets.

**Comment by GeneZC** [comment]
In fact, I did not find the mentioned case through checking, but I guess there might be one.
In addition to that, I have found that there a lot of samples consisting of the same target with different opinion expressions.

**Comment by GeneZC** [comment]
Now I have checked all data. There are no opinion overlapping samples but only target overlapping samples.

**Comment by xuuuluuu** [comment]
These special cases are rare. And if these cases happened, we assign the opinion words to the most likely target.

**Comment by GeneZC** [comment]
Ok, thanks anyway.
